# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "819d952f9b1afcd3aa7c4cd299511fca"
name = "wc-theme-installer"
handle = "wc-theme-installer"
application_url = "https://coordinate-responsibility-consortium-constraints.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://coordinate-responsibility-consortium-constraints.trycloudflare.com/auth/callback", "https://coordinate-responsibility-consortium-constraints.trycloudflare.com/auth/shopify/callback", "https://coordinate-responsibility-consortium-constraints.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
